### ISSUE TITLE
CodeSwing won't run when it's the only extension enabled.

### ISSUE THREAD

**Issue by johnpapa** [codespaces-contrib/codeswing#30] opened 2021-02-15 20:56 UTC
problem:

I disabled all extensions, then enabled CodeSwing. Then reloaded VS Code. However I cannot run any swings. (see below)
![image](https://user-images.githubusercontent.com/1202528/107992224-42266980-6fa6-11eb-97e9-8e8cdf73a3cf.png)

Why? - I was trying to test to see if Svelte apps work without any of my extension favorites.

**Comment by lostintangent** [comment] 2021-02-16 01:26
This is a duplicate of https://github.com/codespaces-contrib/codeswing/issues/4. The issue isn't that CodeSwing depends on other extensions, it's that the preview window isn't re-opened when you reload VS Code. If you run the `CodeSwing: Open Swing` command, and then select your swing directory, it will re-launch the environment 👍 

So I'll go ahead and close this and we can track that discussion in #4.

**Closed by lostintangent** 2021-02-16 01:26 UTC
