### ISSUE TITLE
Creating new swing from template adds

### ISSUE THREAD

**Issue by ryandejaegher** [codespaces-contrib/codeswing#27] opened 2021-02-05 13:29 UTC
I've run into an issue while creating new swings from templates. If I choose one of my existing templates for the new code swing, it will create another template inside the code-swing-template menu instead of adding it to the code-swing menu. 

Is this the correct behaviour. Is there a setting I should change in the codeswing.json file?

![PixelSnap 2021-02-05 at 08 26 33@2x](https://user-images.githubusercontent.com/17536831/107039412-e1b85080-678b-11eb-957d-01a529548371.png)

![image](https://user-images.githubusercontent.com/17536831/107039471-f268c680-678b-11eb-9ba4-b759ef0fdaae.png)

**Comment by lostintangent** [comment] 2021-02-06 06:26
Hey! This is a good find. I can see what the problem is, and I’ll try to get to this tomorrow 👍 In the meantime, you can workaround this by deleting the “template” property in the codeswing.json file. That’s what determines whether a swing is categorized as a template or not, and so I just need to clear that property automatically when creating a swing from a template.

**Comment by ryandejaegher** [comment] 2021-02-10 13:10
Hey @lostintangent awesome! Btw fricken love CodeSwing. It's been a huge boost in my workflow. Keep it up!

**Comment by lostintangent** [comment] 2021-02-12 18:40
This has been fixed and will be released in an update this afternoon 👍

**Closed by lostintangent** 2021-02-12 18:40 UTC
